<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" />
  <PropertyGroup>
    <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
    <Platform Condition="'$(Platform)' == ''">AnyCPU</Platform>
    <OutputType>Exe</OutputType>
    <AssemblyName>InputBreak</AssemblyName>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="TerminalMatrixNetFramework">
      <HintPath>..\..\A-BASIC-Language\A-BASIC-Language\bin\$(Configuration)\TerminalMatrixNetFramework.dll</HintPath>
    </Reference>
    <Compile Include="Program.cs" />
    <ProjectReference Include="..\..\A-BASIC-Language\A-BASIC-Language\A-BASIC-Language.csproj">
      <Project>{E53E225A-6F21-403B-AF6B-0D76D8D974CA}</Project>
      <Name>A-BASIC-Language</Name>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
